kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: raytune-pong
  context: raytune-pong # raytune-pong folder
  dockerfile: ./Dockerfile

spec:
  operator: kuberay
  image: raytune-pong
  command: "python main.py"

  debug:
    jupyter: false

  tensorboard: ## optional, disabled by default
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 2
        ramRatio: 16 # 32GB
        accelerators: # optional
          gpu:
            count: 2 # note that setting more than 1 MIG device per container is useless since only one will be usable https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#cuda-device-enumeration
            type: gpu
            product: NVIDIA-A100-SXM4-40GB
